### ISSUE TITLE
Possible optimization for repbulk

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/proteomicsTumorDeconv#107]
Repbulk takes about a half hour on a dataset. Therefore to do mRNA/prot correlation, that's an hour, and we need do multiple datasets - is there any way to precompute the randomization step and store it in the docker image?

**Comment by sgosline** [comment]
Perhaps allow repbulk to run in a 'single sample' mode, that reads in an existing distribution from a local file. We can store individual files for each cancer  and data modality (e.g. mrna/imputedprot, reg prot)....

**Comment by annapamma** [comment]
@sgosline Do you have a data set I can test the timings on? Thanks!

**Comment by annapamma** [comment]
@sgosline I think the updated code has been relatively optimized. Can you lmk how the timings look next time you run it? Thanks!

**Comment by sgosline** [comment]
Assigning to myself to test.
