### ISSUE TITLE
Come up with tool name

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/proteomicsTumorDeconv#147]
Current idea is DeCom? Can we add 'protein'?

**Comment by sgosline** [comment]
DeComP

**Comment by pietrisko** [comment]
DeCoMP: Deconvolution Comparison of Mrna and Protein data

**Comment by annapamma** [comment]
Decomprolute

**Comment by sgosline** [comment]
Tumor DecoMP: Tumor Deconvolution Metrics Platform

**Comment by sgosline** [comment]
We decided on Decomprolute!
