### ISSUE TITLE
We should consider averaging distance values

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/proteomicsTumorDeconv#151]
I'd like to discuss why we are using this formulation to compare distances. It would seem to me that a mean or median would be ideal, since it doesn't bias larger sample sets.

https://github.com/sgosline/proteomicsTumorDeconv/blob/c6f149e2b2cc607e53bd7589101bef4a3fe76f3d/perfEval/figures/combine_results.R#L151

**Comment by LifeWorks** [comment]
Solved by #158  now it is calculated with mean
