### ISSUE TITLE
Epic failing on LM7c matrix

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/proteomicsTumorDeconv#162]
Running the data simulation i'm failing to get simulated data using lmc7 and epic. I'm nots ure if this is the check.row.names issue that @annapamma brought up.

**Comment by LifeWorks** [comment]
> [1] "/var/lib/cwl/stgd67e41e7-aef5-43a0-9288-c324eee8cad4/data_rep_5_matrix-epic-LM7c.tsv"
> [2] "/var/lib/cwl/stg9a5dcdc7-7e03-402a-ae58-2da5a2456463/LM7c.txt"
> [3] "prot"
> [4] "/var/lib/cwl/stg7681a090-e190-40e3-a68c-dcaf0e1a49f8/data_rep_5_cellPreds.tsv"
> [1] "Sig cell types: B.cells,T4.cells,T8.cells,DC,Granulocytes,MO,NK.cells"
> [1] "Simulated cell types: B cells,T4 cells,T8 cells,DC,NK,MO,Basophil,Eosinophil,Neutrophil"
> [1] "Overlapping cell types before mapping (2): DC,MO"
> [1] "Sig cell types: B.cells,T4.cells,T8.cells,Dendritic cells,Granulocytes,Monocytes,NK.cells"
> [1] "Simulated cell types: B cells,CD4 T cells,CD8 T cells,Dendritic cells,NK cells,MO,Basophil,Eosinophils,Neutrophils"
> [1] "Overlapping cell types after mapping LM7c.txt to prot(1): Dendritic cells"

**Comment by LifeWorks** [comment]
I have some concern about the stored simulated data. All columns in all the data are using the same name "data.s", shouldn't we change that with appending numbers?

**Comment by LifeWorks** [comment]
<img width="1652" alt="Screen Shot 2021-06-18 at 10 19 26 PM" src="https://user-images.githubusercontent.com/1332406/122631802-3eedd800-d083-11eb-9ee5-bd80ae9b5023.png">
Here is a comparison between cellPred file and deconvoluted file. From results using LM7c with EPIC, they are different in both rownames and colnames.

**Comment by LifeWorks** [comment]
I will try to rename all the columns in the stored simulated data

**Comment by sgosline** [comment]
Yeah, that's not a bad idea. The simulated data docker is a bit of  a kludge right now.

**Comment by LifeWorks** [comment]
Fixed the bugs. It turned out that the LM7c data stored for EPIC docker images were contaminated.  You might want to clear your docker image after you merge the pull request.
