### ISSUE TITLE
DockerHub no longer auto building

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/proteomicsTumorDeconv#166]
So docker hub stopped autobuilding from github under the 'free' site. I think we have a few options:

1- pay for docker hub, this would be tricky
2- create a script that builds all docker images locally
3- create a .circleci test that builds new docker images any time the files have been updated and puts them onto docker hub for us (can we do this?)
4- manually upload docker images to docker hub

I'm a fan of 3 if possible, and 2 as  a second best. Thoughts?

**Comment by annapamma** [comment]
Confirmed possible with CircleCI. 

To prevent using up all of the CircleCI credits, I have set a branch filter so branches must be explicitly named "docker-" to build and push images to Dockerhub.

As of July 13, it seems that the images are still auto-building. We'll table this for now and close the issue, but can reopen in case auto-building stops.

**Comment by sgosline** [comment]
Update from docker:
```
As you may remember, on June 7, 2021 we announced the end of Autobuilds for all free accounts and starting on Monday, July 26, 2021 all Autobuilds associated with a free account will be disabled and stop working. 
```

**Comment by annapamma** [comment]
- Can now autobuild and push via CircleCI
- Specifically building the TumorDeconvAlgs Docker files
- Let me know if you want to add any other Docker images from additional modules

Example pipeline:
https://app.circleci.com/pipelines/github/PNNL-CompBio/proteomicsTumorDeconv/418/workflows/5ba1cc7c-6de9-439e-b77c-eb0bd5627af7
