### ISSUE TITLE
Build and push Docker images automatically

### ISSUE THREAD

**Issue by annapamma** [PNNL-CompBio/proteomicsTumorDeconv#182]
Goal: with each commit, build and push Docker images

**Comment by annapamma** [comment]
These are the Docker images I'm testing, please let me know if I missed any:

- tumordeconv/prot-data 
- tumordeconv/signature_matrices
- tumordeconv/mrna-data

metrics/
- tumordeconv/correlation
- tumordeconv/comparison
- tumordeconv/figures
- tumordeconv/imm-subtypes

tumorDeconvAlgs/
- tumordeconv/cibersort
- tumordeconv/epic
- tumordeconv/mcpcounter
- tumordeconv/xcell

**Comment by sgosline** [comment]
Hi Anna,

We renamed correlation to correlations, and comparison to distance.

**Comment by annapamma** [comment]
Pushed a commit last night and this works!

Just open a new issue if any Docker images are added.
